### ISSUE TITLE
CatBoost Issue

### ISSUE THREAD

**Issue by abinaybingumalla** [HackerEarth-Challenges/Happiness-ML-Challenge#1]
I am trying to run  cross validation and its in running state even after 1hr in Macbook Pro
8GB Ram 2.9 GHz Intel Core i5 with Intel Iris Graphics 6100 1536 MB.

I am doing something wrong or how long this cross validation step will take.

(## run cv to get best iteration ctb_cv = cv(param, my_dt, fold_count=5, random_seed=2017))

**Comment by saraswatmks** [comment]
@abinaybingumalla  Looks like you are doing CV on too many features. 
You can:
1. Reduce the feature count from whatever feature creating technique (CountVectorizer or TF-IDF you are using.
2. Use PCA to reduce the dimension. 

It shouldn't take much time. We'll soon share AWS access. Keep a check on competition page.
